### ISSUE TITLE
Hi does this allow multiple Twitter account "pulls"?

### ISSUE THREAD

**Issue by hjgabrielsen** [ibrennan/Parse-Cloud-Code-Cache-Tweets#1]

**Comment by ibrennan** [comment]
Hi @hjgabrielsen,

It doesn't support doing multiple accounts straight off the bat, but with a few small modifications it could do.

If you'd like, I can take a look at modifying the script over the next couple of days and post an update that takes an array of Twitter accounts, rather than a single one.

**Comment by hjgabrielsen** [comment]
That would be great!

**Comment by ibrennan** [comment]
Just on this, the ideal solution would be to allow multiple schedules of the same job in Parse and then pass in the JSON Param to define which twitter account you want to fetch. I've raised a feature request for this: https://groups.google.com/forum/#!topic/parse-developers/6IpCNG736gw

But for now I'll create a way to do it through code.

**Comment by hjgabrielsen** [comment]
I posted almost the same question on StackOverflow.. 

http://stackoverflow.com/questions/30739398/cloud-code-w-multiple-js-files-that-grabs-twitterfeeds-but-only-one-available

**Comment by ibrennan** [comment]
Hi @hjgabrielsen 

I've pushed an update of the script, it now accepts an array of usernames to cache. 

It uses Promises to ensure the async calls don't interfere with one another (https://parse.com/docs/js/guide#promises)

Let me know how you get on!

**Comment by hjgabrielsen** [comment]
Thanks !
